# Название нашего приложения
spring.application.name=library-core

# Настройка подключения к PostgreSQL (Реляционная БД для пользователей)
spring.datasource.url=jdbc:postgresql://localhost:5432/library_db
spring.datasource.username=lib_user
spring.datasource.password=LibPassword123!
spring.datasource.driver-class-name=org.postgresql.Driver

# Настройки Hibernate/JPA
# update автоматический создает таблицы в БД на основе наших Java-классов @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Настройка подключения к ElasticSearch (Поисковый движок для книг)
spring.elasticsearch.uris=http://localhost:9200

# Настройки логирования (чтобы в консоли видеть, если что-то пойдет не так)
logging.level.org.springframework.data.elasticsearch=DEBUG
logging.level.org.hibernate.SQL=DEBUG

spring.jpa.hibernate.ddl-auto=update